# Generated by Django 2.1.3 on 2018-11-23 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(null=True)),
                ('bio', models.CharField(max_length=420, null=True)),
                ('followers', models.ManyToManyField(to='coolcars.Info')),
            ],
        ),
    ]
