# Generated by Django 2.1.3 on 2018-12-01 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coolcars', '0003_auto_20181125_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
