# Generated by Django 2.1.3 on 2018-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolcars', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
