# Generated by Django 2.1.3 on 2018-12-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolcars', '0009_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='tags',
            new_name='searches',
        ),
    ]
